### ISSUE TITLE
URL in repository description gives error 403

### ISSUE THREAD

**Issue by jacobdeichert** [summerAI/summerai.github.io#1]
Just letting you know that [www.knot63.com](http://www.knot63.com) gives a forbidden access error while [knot63.com](http://knot63.com) works fine.

**Comment by jacobdeichert** [comment]
@maebert bump? lol

**Comment by maebert** [comment]
Hm, `www` should do a 301 redirect to knot63.com. Are you maybe auto completing to `https`? We don't have our Certs set up yet :-/

**Comment by jacobdeichert** [comment]
All of a sudden it works now? Hmmm weird, it wouldn't go for the last 10 days.

**Comment by maebert** [comment]
Yay, first issue resolved. 🍪
